### ISSUE TITLE
[bug]某些视频无法播放

### ISSUE THREAD

**Issue by dxuser114** [xiaye13579/BBLL#938]
在安卓4.4.2的设备上播放一些视频时提示Source error，更改视频编码，降低画质，更改音频音质均无法播放，软件是最新版的

**Comment by dxuser114** [comment]
另外，附上logcat:
E/ExoPlayerImplInternal(31213): Playback error                                                                                      E/ExoPlayerImplInternal(31213):   androidx.media3.exoplayer.ExoPlaybackException: Source error                                      E/ExoPlayerImplInternal(31213):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:701)                                                                                                                              E/ExoPlayerImplInternal(31213):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:673)                                                                                                                                  E/ExoPlayerImplInternal(31213):       at android.os.Handler.dispatchMessage(Handler.java:98)                                        E/ExoPlayerImplInternal(31213):       at android.os.Looper.loop(Looper.java:136)                                                    E/ExoPlayerImplInternal(31213):       at android.os.HandlerThread.run(HandlerThread.java:61)                                        E/ExoPlayerImplInternal(31213):   Caused by: androidx.media3.datasource.HttpDataSource$HttpDataSourceException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.                      E/ExoPlayerImplInternal(31213):       at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:405)      E/ExoPlayerImplInternal(31213):       at androidx.media3.datasource.ResolvingDataSource.open(ResolvingDataSource.java:110)          E/ExoPlayerImplInternal(31213):       at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)                   E/ExoPlayerImplInternal(31213):       at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1029)                                                                                                              E/ExoPlayerImplInternal(31213):       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:417)                    E/ExoPlayerImplInternal(31213):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)            E/ExoPlayerImplInternal(31213):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)            E/ExoPlayerImplInternal(31213):       at java.lang.Thread.run(Thread.java:841)                                                      E/ExoPlayerImplInternal(31213):   Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.                                                                                         E/ExoPlayerImplInternal(31213):       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:410)     E/ExoPlayerImplInternal(31213):       at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)                            E/ExoPlayerImplInternal(31213):       at com.android.okhttp.Connection.connect(Connection.java:107)                                 E/ExoPlayerImplInternal(31213):       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)                   E/ExoPlayerImplInternal(31213):       at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)         E/ExoPlayerImplInternal(31213):       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)               E/ExoPlayerImplInternal(31213):       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)                                                                                                                                 E/ExoPlayerImplInternal(31213):       at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)                                                                                                                                  E/ExoPlayerImplInternal(31213):       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161)                                                                                                                               E/ExoPlayerImplInternal(31213):       at androidx.media3.datasource.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:678)                                                                                                                                E/ExoPlayerImplInternal(31213):       at androidx.media3.datasource.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:559)                                                                                                                                E/ExoPlayerImplInternal(31213):       at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:399)      E/ExoPlayerImplInternal(31213):       ... 7 more                                                                                    E/ExoPlayerImplInternal(31213):   Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.                                                                                     E/ExoPlayerImplInternal(31213):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:282)         E/ExoPlayerImplInternal(31213):       at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:202)   E/ExoPlayerImplInternal(31213):       at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:612)                                                                                                                                 E/ExoPlayerImplInternal(31213):       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)                     E/ExoPlayerImplInternal(31213):       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)     E/ExoPlayerImplInternal(31213):       ... 18 more                                                                                   E/ExoPlayerImplInternal(31213):   Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.                                                                                                                              E/ExoPlayerImplInternal(31213):       ... 23 more

**Comment by dxuser114** [comment]
已解决
